# Checkpoint Three: Cleaning Data

Now you are ready to clean your data. Before starting coding, provide the link to your dataset below.

My dataset: https://www.ncei.noaa.gov/cdo-web/datasets/GHCND/locations/ZIP:64116/detail

Import the necessary libraries and create your dataframe(s).

In [1]:
# import libraries
import pandas as pd
import numpy as np
import seaborn as sb
import plotly.express as px
import matplotlib.pyplot as plt
from matplotlib import style

# read in .csv file as dataframe (from checkpoint 2)
weather_df = pd.read_csv('WeatherData.csv')
# remove duplicated index column
weather_df = weather_df.drop(['Unnamed: 0'],axis=1)
# view sample
weather_df.head(25)

,STATION,NAME,DATE,Avg Daily Cloudiness (%),Avg Solar Day Cloudiness (%),Avg Daily Wind Speed (mph),Days in Multiday Precipitation,Fastest Wind Time (HH:MM),Base of Frozen Ground Layer (inches),Top of Frozen Ground Layer (inches),...,Weather Type - Freezing Drizzle,Weather Type - Rain,Weather Type - Freezing Rain,Weather Type - Snow,Weather Type - Ice Fog or Freezing Fog,Year,Month,Day,Month & Day,Year & Month
0,USW00013988,"KANSAS CITY DOWNTOWN AIRPORT, MO US",1934-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.0,NaN,1.0,NaN,1934,1,1,01-01,1934-01
1,USW00013988,"KANSAS CITY DOWNTOWN AIRPORT, MO US",1934-01-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1.0,NaN,1934,1,2,01-02,1934-01
2,USW00013988,"KANSAS CITY DOWNTOWN AIRPORT, MO US",1934-01-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.0,NaN,1.0,NaN,1934,1,3,01-03,1934-01
3,USW00013988,"KANSAS CITY DOWNTOWN AIRPORT, MO US",1934-01-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.0,NaN,1.0,NaN,1934,1,4,01-04,1934-01
4,USW00013988,"KANSAS CITY DOWNTOWN AIRPORT, MO US",1934-01-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1.0,NaN,1934,1,5,01-05,1934-01
5,USW00013988,"KANSAS CITY DOWNTOWN AIRPORT, MO US",1934-01-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.0,NaN,NaN,NaN,1934,1,6,01-06,1934-01
6,USW00013988,"KANSAS CITY DOWNTOWN AIRPORT, MO US",1934-01-07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.0,NaN,1.0,NaN,1934,1,7,01-07,1934-01
7,USW00013988,"KANSAS CITY DOWNTOWN AIRPORT, MO US",1934-01-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1.0,NaN,1934,1,8,01-08,1934-01
8,USW00013988,"KANSAS CITY DOWNTOWN AIRPORT, MO US",1934-01-09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.0,NaN,1.0,NaN,1934,1,9,01-09,1934-01
9,USW00013988,"KANSAS CITY DOWNTOWN AIRPORT, MO US",1934-01-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1.0,NaN,1934,1,10,01-10,1934-01
10,USW00013988,"KANSAS CITY DOWNTOWN AIRPORT, MO US",1934-01-11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1934,1,11,01-11,1934-01
11,USW00013988,"KANSAS CITY DOWNTOWN AIRPORT, MO US",1934-01-12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.0,NaN,1.0,NaN,1934,1,12,01-12,1934-01
12,USW00013988,"KANSAS CITY DOWNTOWN AIRPORT, MO US",1934-01-13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1.0,NaN,1934,1,13,01-13,1934-01
13,USW00013988,"KANSAS CITY DOWNTOWN AIRPORT, MO US",1934-01-14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1934,1,14,01-14,1934-01
14,USW00013988,"KANSAS CITY DOWNTOWN AIRPORT, MO US",1934-01-15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1934,1,15,01-15,1934-01
15,USW00013988,"KANSAS CITY DOWNTOWN AIRPORT, MO US",1934-01-16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1934,1,16,01-16,1934-01
16,USW00013988,"KANSAS CITY DOWNTOWN AIRPORT, MO US",1934-01-17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1934,1,17,01-17,1934-01
17,USW00013988,"KANSAS CITY DOWNTOWN AIRPORT, MO US",1934-01-18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1934,1,18,01-18,1934-01
18,USW00013988,"KANSAS CITY DOWNTOWN AIRPORT, MO US",1934-01-19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1934,1,19,01-19,1934-01
19,USW00013988,"KANSAS CITY DOWNTOWN AIRPORT, MO US",1934-01-20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1934,1,20,01-20,1934-01
20,USW00013988,"KANSAS CITY DOWNTOWN AIRPORT, MO US",1934-01-21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1934,1,21,01-21,1934-01
21,USW00013988,"KANSAS CITY DOWNTOWN AIRPORT, MO US",1934-01-22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.0,NaN,NaN,NaN,1934,1,22,01-22,1934-01
22,USW00013988,"KANSAS CITY DOWNTOWN AIRPORT, MO US",1934-01-23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1934,1,23,01-23,1934-01
23,USW00013988,"KANSAS CITY DOWNTOWN AIRPORT, MO US",1934-01-24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1934,1,24,01-24,1934-01
24,USW00013988,"KANSAS CITY DOWNTOWN AIRPORT, MO US",1934-01-25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1934,1,25,01-25,1934-01

## Missing Data

Test your dataset for missing data and handle it as needed. Make notes in the form of code comments as to your thought process.

In [2]:
# Get info about dataframe
weather_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32138 entries, 0 to 32137
Data columns (total 56 columns):
 #   Column                                            Non-Null Count  Dtype
---  ------                                            --------------  -----
 0   STATION                                           32138 non-null  object
 1   NAME                                              32138 non-null  object
 2   DATE                                              32138 non-null  object
 3   Avg Daily Cloudiness (%)                          3886 non-null   float64
 4   Avg Solar Day Cloudiness (%)                      3886 non-null   float64
 5   Avg Daily Wind Speed (mph)                        10904 non-null  float64
 6   Days in Multiday Precipitation                    11 non-null     float64
 7   Fastest Wind Time (HH:MM)                         3875 non-null   float64
 8   Base of Frozen Ground Layer (inches)              5 non-null      float64
 9   Top of Frozen Ground Layer (inches)               6 non-null      float64
 10  Thickness of Frozen Ground Layer (inches)         5 non-null      float64
 11  Distance Between River and Gauge Height (inches)  6203 non-null   float64
 12  Multiday Precipitation Total (inches)             14 non-null     float64
 13  Peak Gust Time (HH:MM)                            5274 non-null   float64
 14  Precipitation (inches)                            32050 non-null  float64
 15  Daily % of Possible Sunshine                      2835 non-null   float64
 16  Snowfall (inches)                                 26613 non-null  float64
 17  Snow Depth (inches)                               24103 non-null  float64
 18  Avg Hourly Temp (Fahrenheit)                      2677 non-null   float64
 19  Highest Hourly Temp (Fahrenheit)                  29934 non-null  float64
 20  Lowest Hourly Temp (Fahrenheit)                   29931 non-null  float64
 21  Temperature at Observation (Fahrenheit)           2768 non-null   float64
 22  Daily Total Sunshine (minutes)                    4058 non-null   float64
 23  Direction of Fastest 1-Minute Wind (degrees)      1056 non-null   float64
 24  Direction of Fastest 2-Minute Wind (degrees)      9180 non-null   float64
 25  Direction of Fastest 5-Minute Wind (degrees)      9174 non-null   float64
 26  Direction of Peak Wind Gust (degrees)             491 non-null    float64
 27  Fastest mile wind direction (degrees)             2830 non-null   float64
 28  Water Equivalent of Snow on the Ground (inches)   426 non-null    float64
 29  Water-equivalent of Snowfall (inches)             14 non-null     float64
 30  Fastest 1-minute wind speed (mph)                 1055 non-null   float64
 31  Fastest 2-minute wind speed (mph)                 9180 non-null   float64
 32  Fastest 5-minute wind speed (mph)                 9174 non-null   float64
 33  Peak Guest Wind Speed (mph)                       494 non-null    float64
 34  Fastest mile wind speed (mph)                     2830 non-null   float64
 35  Weather Type - Fog                                6852 non-null   float64
 36  Weather Type - Heavy or Freezing Fog              255 non-null    float64
 37  Weather Type - Thunder                            3624 non-null   float64
 38  Weather Type - Ice Pellets                        304 non-null    float64
 39  Weather Type - Hail                               207 non-null    float64
 40  Weather Type - Glaze or rime                      414 non-null    float64
 41  Weather Type - Dust, Volcanic Ash, Blowing Dust   132 non-null    float64
 42  Weather Type - Smoke or Haze                      9311 non-null   float64
 43  Weather Type - Blowing or Drifting Snow           121 non-null    float64
 44  Weather Type - High or Damaging Winds             59 non-null     float64
 45  Weather Type - Drizzle                            336 non-null    float64
 46  Weather Type - Freezing Drizzle                   26 non-null     float64
 47  Weather Type - Rain                               6430 non-null   float64
 48  Weather Type - Freezing Rain                      13 non-null     float64
 49  Weather Type - Snow                               1754 non-null   float64
 50  Weather Type - Ice Fog or Freezing Fog            3 non-null      float64
 51  Year                                              32138 non-null  int64
 52  Month                                             32138 non-null  int64
 53  Day                                               32138 non-null  int64
 54  Month & Day                                       32138 non-null  object
 55  Year & Month                                      32138 non-null  object
dtypes: float64(48), int64(3), object(5)
memory usage: 13.7+ MB

In [3]:
# Check for duplicate dates. I will be eliminating the NKC station so will compare the total downtown station records against unique dates for those records.
print('{0} records\n{1} dates'.format(len(weather_df[weather_df['STATION']=='USW00013988']),len(weather_df[weather_df['STATION']=='USW00013988']['DATE'].unique())))

29970 records
29970 dates

In [4]:
# Check for number of records missing any of the key three data points (lowest temp, highest temp, precipitation)
weather_df_downtown = weather_df[weather_df['STATION']=='USW00013988']
Missing_Data = weather_df_downtown[(weather_df_downtown['Lowest Hourly Temp (Fahrenheit)'].isna()) | (weather_df_downtown['Highest Hourly Temp (Fahrenheit)'].isna()) | (weather_df_downtown['Precipitation (inches)'].isna())]
len(Missing_Data)

101

In [5]:
# Remove records that are missing all three key data points
# records_to_remove = Missing_Data[(Missing_Data['Lowest Hourly Temp (Fahrenheit)'].isna()) & (Missing_Data['Highest Hourly Temp (Fahrenheit)'].isna()) & (Missing_Data['Precipitation (inches)'].isna())].index
# weather_df.drop(records_to_remove,inplace=True)
# Missing_Data.drop(records_to_remove,inplace=True)
# print('{0} total records\n{1} records missing data'.format(len(weather_df[weather_df['STATION']=='USW00013988']),len(Missing_Data)))
# records_to_remove

Int64Index([20162, 23264, 25869], dtype='int64')

In [6]:
# Review remaining missing data starting with precipitation
# Find dates of records missing the precipitation data point
Dates_missing_precipitation = Missing_Data[Missing_Data['Precipitation (inches)'].isna()]['DATE'].values
Dates_missing_precipitation

array(['1981-05-22', '1985-05-26', '1985-05-27', '1988-09-23',
       '1988-09-24', '1988-09-28', '1988-09-29', '1988-09-30',
       '1995-01-01', '1995-01-02', '1995-01-03', '1995-01-04',
       '1995-01-07', '1995-01-08', '1995-01-09', '1995-01-10',
       '1995-01-11', '1995-01-12', '1995-01-13', '1995-01-14',
       '1995-01-15', '1995-01-20', '1995-01-21', '1995-01-22',
       '1995-01-23', '1995-01-24', '1995-01-25', '1995-01-29',
       '1995-01-30', '1995-01-31', '1996-01-03', '1996-07-14',
       '1996-07-15', '1998-03-08', '2005-01-10', '2012-02-28',
       '2015-04-26', '2016-12-16', '2018-08-14', '2018-08-15',
       '2018-08-16', '2018-08-28', '2018-09-28', '2018-10-12',
       '2018-11-08', '2019-03-03', '2019-03-12', '2020-01-22',
       '2020-02-12', '2020-04-24', '2020-04-25', '2020-09-05',
       '2021-01-15', '2021-04-08', '2021-04-28', '2021-10-12',
       '2021-10-13', '2022-01-15', '2022-07-26', '2022-07-27',
       '2022-08-16', '2023-04-10'], dtype=object)

In [7]:
# Display records for both stations on records missing precipation data
Records_missing_precipitation = weather_df[weather_df['DATE'].isin(Dates_missing_precipitation)]
Precipitation_Duplicated_Dates = Records_missing_precipitation[Records_missing_precipitation['DATE'].duplicated()]['DATE'].values
weather_df[weather_df['DATE'].isin(Precipitation_Duplicated_Dates)][{'STATION','Precipitation (inches)','DATE'}]

/var/folders/n7/v6st_7m50r399qhl3pcqrdmh0000gn/T/ipykernel_3752/1873684866.py:4: FutureWarning: Passing a set as an indexer is deprecated and will raise in a future version. Use a list instead.
  weather_df[weather_df['DATE'].isin(Precipitation_Duplicated_Dates)][{'STATION','Precipitation (inches)','DATE'}]

       Precipitation (inches)      STATION        DATE
27022                     NaN  USW00013988  2015-04-26
27622                     NaN  USW00013988  2016-12-16
31138                    0.35  US1MOCY0003  2015-04-26
31699                    0.00  US1MOCY0003  2016-12-16

In [8]:
# Sub NKC station precipitation data for missing Downtown precipitation data
weather_df['Precipitation (inches)'][27022] = weather_df['Precipitation (inches)'][31138]
weather_df['Precipitation (inches)'][27622] = weather_df['Precipitation (inches)'][31699]
# Ensure temperature data is not also missing for these records
weather_df[weather_df['DATE'].isin(Precipitation_Duplicated_Dates)][{'STATION','Precipitation (inches)','DATE','Lowest Hourly Temp (Fahrenheit)','Highest Hourly Temp (Fahrenheit)'}]

/var/folders/n7/v6st_7m50r399qhl3pcqrdmh0000gn/T/ipykernel_3752/1001771695.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weather_df['Precipitation (inches)'][27022] = weather_df['Precipitation (inches)'][31138]
/var/folders/n7/v6st_7m50r399qhl3pcqrdmh0000gn/T/ipykernel_3752/1001771695.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weather_df['Precipitation (inches)'][27622] = weather_df['Precipitation (inches)'][31699]
/var/folders/n7/v6st_7m50r399qhl3pcqrdmh0000gn/T/ipykernel_3752/1001771695.py:5: FutureWarning: Passing a set as an indexer is deprecated and will raise in a future version. Use a list instead.
  weather_df[weather_df['DATE'].isin(Precipitation_Duplicated_Dates)][{'STATION','Precipitation (inches)','DATE','Lowest Hourly Temp (Fahrenheit)','Highest Hourly Temp (Fahrenheit)'}]

,STATION,Lowest Hourly Temp (Fahrenheit),Precipitation (inches),DATE,Highest Hourly Temp (Fahrenheit)
27022,USW00013988,49.0,0.35,2015-04-26,64.0
27622,USW00013988,27.0,0.00,2016-12-16,33.0
31138,US1MOCY0003,NaN,0.35,2015-04-26,NaN
31699,US1MOCY0003,NaN,0.00,2016-12-16,NaN

In [9]:
# Remove records from missing data list now that they have been resolved.
Missing_Data.drop(index={27022,27622},axis=0,inplace=True)
len(Missing_Data)

/var/folders/n7/v6st_7m50r399qhl3pcqrdmh0000gn/T/ipykernel_3752/40950122.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Missing_Data.drop(index={27022,27622},axis=0,inplace=True)

99

In [10]:
# Isolate relevant columns for remaining missing data to determine if there are clues to fill in data.

Missing_Data_Limit = Missing_Data.loc[:,('NAME','DATE','Days in Multiday Precipitation','Multiday Precipitation Total (inches)','Precipitation (inches)','Snowfall (inches)','Avg Hourly Temp (Fahrenheit)','Highest Hourly Temp (Fahrenheit)','Lowest Hourly Temp (Fahrenheit)','Temperature at Observation (Fahrenheit)','Water Equivalent of Snow on the Ground (inches)','Water-equivalent of Snowfall (inches)','Weather Type - Ice Pellets','Weather Type - Hail','Weather Type - Drizzle','Weather Type - Freezing Drizzle','Weather Type - Rain','Weather Type - Freezing Rain','Weather Type - Snow')]
Missing_Data_Limit

,NAME,DATE,Days in Multiday Precipitation,Multiday Precipitation Total (inches),Precipitation (inches),Snowfall (inches),Avg Hourly Temp (Fahrenheit),Highest Hourly Temp (Fahrenheit),Lowest Hourly Temp (Fahrenheit),Temperature at Observation (Fahrenheit),Water Equivalent of Snow on the Ground (inches),Water-equivalent of Snowfall (inches),Weather Type - Ice Pellets,Weather Type - Hail,Weather Type - Drizzle,Weather Type - Freezing Drizzle,Weather Type - Rain,Weather Type - Freezing Rain,Weather Type - Snow
15056,"KANSAS CITY DOWNTOWN AIRPORT, MO US",1981-05-22,NaN,NaN,NaN,0.0,NaN,85.0,69.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN
15795,"KANSAS CITY DOWNTOWN AIRPORT, MO US",1983-05-31,NaN,NaN,0.0,0.0,NaN,NaN,51.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16521,"KANSAS CITY DOWNTOWN AIRPORT, MO US",1985-05-26,NaN,NaN,NaN,0.0,NaN,93.0,66.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN
16522,"KANSAS CITY DOWNTOWN AIRPORT, MO US",1985-05-27,NaN,NaN,NaN,0.0,NaN,72.0,63.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN
17737,"KANSAS CITY DOWNTOWN AIRPORT, MO US",1988-09-23,NaN,NaN,NaN,0.0,NaN,69.0,59.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29478,"KANSAS CITY DOWNTOWN AIRPORT, MO US",2022-01-15,NaN,NaN,NaN,NaN,NaN,33.0,21.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29670,"KANSAS CITY DOWNTOWN AIRPORT, MO US",2022-07-26,NaN,NaN,NaN,NaN,NaN,79.0,66.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29671,"KANSAS CITY DOWNTOWN AIRPORT, MO US",2022-07-27,NaN,NaN,NaN,NaN,NaN,87.0,70.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29691,"KANSAS CITY DOWNTOWN AIRPORT, MO US",2022-08-16,NaN,NaN,NaN,NaN,NaN,72.0,65.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29928,"KANSAS CITY DOWNTOWN AIRPORT, MO US",2023-04-10,NaN,NaN,NaN,NaN,NaN,71.0,54.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
# Review values present for each column
Missing_Data_Limit.columns
for i in Missing_Data_Limit.columns:
    print(Missing_Data_Limit[i].value_counts())
    print('\n')

KANSAS CITY DOWNTOWN AIRPORT, MO US    99
Name: NAME, dtype: int64


1981-05-22    1
2017-07-28    1
2017-06-08    1
2017-05-01    1
2017-04-30    1
             ..
1995-01-25    1
1995-01-24    1
1995-01-23    1
1995-01-22    1
2023-04-10    1
Name: DATE, Length: 99, dtype: int64


2.0    1
Name: Days in Multiday Precipitation, dtype: int64


0.2    1
Name: Multiday Precipitation Total (inches), dtype: int64


0.00    34
0.20     1
0.15     1
1.50     1
0.12     1
1.87     1
Name: Precipitation (inches), dtype: int64


0.0    32
0.1     1
2.5     1
Name: Snowfall (inches), dtype: int64


0.0    2
Name: Avg Hourly Temp (Fahrenheit), dtype: int64


36.0    5
37.0    5
49.0    3
42.0    3
33.0    2
92.0    2
86.0    2
26.0    2
32.0    2
23.0    2
67.0    2
70.0    2
79.0    2
75.0    2
72.0    2
64.0    1
38.0    1
96.0    1
55.0    1
85.0    1
68.0    1
91.0    1
53.0    1
78.0    1
87.0    1
89.0    1
58.0    1
84.0    1
62.0    1
61.0    1
81.0    1
28.0    1
93.0    1
41.0    1
43.0    1
16.0    1
22.0    1
82.0    1
69.0    1
71.0    1
Name: Highest Hourly Temp (Fahrenheit), dtype: int64


21.0    6
50.0    4
24.0    3
66.0    3
59.0    3
73.0    2
19.0    2
74.0    2
34.0    2
33.0    2
26.0    2
70.0    2
54.0    2
11.0    2
58.0    2
32.0    1
30.0    1
43.0    1
45.0    1
72.0    1
31.0    1
47.0    1
5.0     1
69.0    1
25.0    1
22.0    1
17.0    1
51.0    1
28.0    1
18.0    1
4.0     1
7.0     1
12.0    1
64.0    1
63.0    1
65.0    1
Name: Lowest Hourly Temp (Fahrenheit), dtype: int64


25.0    3
28.0    3
26.0    2
24.0    2
32.0    2
15.0    1
33.0    1
71.0    1
59.0    1
43.0    1
29.0    1
42.0    1
41.0    1
35.0    1
27.0    1
22.0    1
9.0     1
11.0    1
80.0    1
Name: Temperature at Observation (Fahrenheit), dtype: int64


Series([], Name: Water Equivalent of Snow on the Ground (inches), dtype: int64)


Series([], Name: Water-equivalent of Snowfall (inches), dtype: int64)


1.0    1
Name: Weather Type - Ice Pellets, dtype: int64


1.0    1
Name: Weather Type - Hail, dtype: int64


Series([], Name: Weather Type - Drizzle, dtype: int64)


Series([], Name: Weather Type - Freezing Drizzle, dtype: int64)


1.0    8
Name: Weather Type - Rain, dtype: int64


Series([], Name: Weather Type - Freezing Rain, dtype: int64)


Series([], Name: Weather Type - Snow, dtype: int64)

In [12]:
# Are there any records where precipitation is null and Weather Type - Rain is 0?  If so, we will fill in precipitation as 0.
Missing_Data[(Missing_Data['Precipitation (inches)'].isna()) & (Missing_Data['Weather Type - Rain']==0)]

Empty DataFrame
Columns: [STATION, NAME, DATE, Avg Daily Cloudiness (%), Avg Solar Day Cloudiness (%), Avg Daily Wind Speed (mph), Days in Multiday Precipitation, Fastest Wind Time (HH:MM), Base of Frozen Ground Layer (inches), Top of Frozen Ground Layer (inches), Thickness of Frozen Ground Layer (inches), Distance Between River and Gauge Height (inches), Multiday Precipitation Total (inches), Peak Gust Time (HH:MM), Precipitation (inches), Daily % of Possible Sunshine, Snowfall (inches), Snow Depth (inches), Avg Hourly Temp (Fahrenheit), Highest Hourly Temp (Fahrenheit), Lowest Hourly Temp (Fahrenheit), Temperature at Observation (Fahrenheit), Daily Total Sunshine (minutes), Direction of Fastest 1-Minute Wind (degrees), Direction of Fastest 2-Minute Wind (degrees), Direction of Fastest 5-Minute Wind (degrees), Direction of Peak Wind Gust (degrees), Fastest mile wind direction (degrees), Water Equivalent of Snow on the Ground (inches), Water-equivalent of Snowfall (inches), Fastest 1-minute wind speed (mph), Fastest 2-minute wind speed (mph), Fastest 5-minute wind speed (mph), Peak Guest Wind Speed (mph), Fastest mile wind speed (mph), Weather Type - Fog, Weather Type - Heavy or Freezing Fog, Weather Type - Thunder, Weather Type - Ice Pellets, Weather Type - Hail, Weather Type - Glaze or rime, Weather Type - Dust, Volcanic Ash, Blowing Dust, Weather Type - Smoke or Haze, Weather Type - Blowing or Drifting Snow, Weather Type - High or Damaging Winds, Weather Type - Drizzle, Weather Type - Freezing Drizzle, Weather Type - Rain, Weather Type - Freezing Rain, Weather Type - Snow, Weather Type - Ice Fog or Freezing Fog, Year, Month, Day, Month & Day, Year & Month]
Index: []

[0 rows x 56 columns]

In [13]:
# Does Avg Hourly Temp (Fahrenheit) or Temperature at Observation (Fahrenheit) provide any information for records missing highest and lowest temp?

Missing_Data_Limit[((Missing_Data_Limit['Highest Hourly Temp (Fahrenheit)'].isna()) | (Missing_Data['Lowest Hourly Temp (Fahrenheit)'].isna())) & ((Missing_Data_Limit['Avg Hourly Temp (Fahrenheit)'].notna()) | (Missing_Data['Temperature at Observation (Fahrenheit)'].notna()))]

,NAME,DATE,Days in Multiday Precipitation,Multiday Precipitation Total (inches),Precipitation (inches),Snowfall (inches),Avg Hourly Temp (Fahrenheit),Highest Hourly Temp (Fahrenheit),Lowest Hourly Temp (Fahrenheit),Temperature at Observation (Fahrenheit),Water Equivalent of Snow on the Ground (inches),Water-equivalent of Snowfall (inches),Weather Type - Ice Pellets,Weather Type - Hail,Weather Type - Drizzle,Weather Type - Freezing Drizzle,Weather Type - Rain,Weather Type - Freezing Rain,Weather Type - Snow
19679,"KANSAS CITY DOWNTOWN AIRPORT, MO US",1995-03-19,NaN,NaN,0.2,NaN,NaN,70.0,NaN,59.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20502,"KANSAS CITY DOWNTOWN AIRPORT, MO US",1997-06-19,NaN,NaN,0.0,0.0,NaN,92.0,NaN,80.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23264,"KANSAS CITY DOWNTOWN AIRPORT, MO US",2005-01-10,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23265,"KANSAS CITY DOWNTOWN AIRPORT, MO US",2005-01-11,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
# For records 19679 & 20502, was temp at observation actually the low temp?
# Check date before and after record 19679 for temp data
weather_df[(weather_df['DATE']=='1995-03-18') | (weather_df['DATE']=='1995-03-20')][{'Highest Hourly Temp (Fahrenheit)','Lowest Hourly Temp (Fahrenheit)'}]

/var/folders/n7/v6st_7m50r399qhl3pcqrdmh0000gn/T/ipykernel_3752/616806541.py:3: FutureWarning: Passing a set as an indexer is deprecated and will raise in a future version. Use a list instead.
  weather_df[(weather_df['DATE']=='1995-03-18') | (weather_df['DATE']=='1995-03-20')][{'Highest Hourly Temp (Fahrenheit)','Lowest Hourly Temp (Fahrenheit)'}]

       Lowest Hourly Temp (Fahrenheit)  Highest Hourly Temp (Fahrenheit)
19678                             52.0                              76.0
19680                             48.0                              62.0

In [15]:
# Check date before and after record 20502 for temp data
weather_df[(weather_df['DATE']=='1997-06-18') | (weather_df['DATE']=='1997-06-20')][{'Highest Hourly Temp (Fahrenheit)','Lowest Hourly Temp (Fahrenheit)'}]

/var/folders/n7/v6st_7m50r399qhl3pcqrdmh0000gn/T/ipykernel_3752/4245900804.py:2: FutureWarning: Passing a set as an indexer is deprecated and will raise in a future version. Use a list instead.
  weather_df[(weather_df['DATE']=='1997-06-18') | (weather_df['DATE']=='1997-06-20')][{'Highest Hourly Temp (Fahrenheit)','Lowest Hourly Temp (Fahrenheit)'}]

       Lowest Hourly Temp (Fahrenheit)  Highest Hourly Temp (Fahrenheit)
20501                             69.0                              90.0
20503                             72.0                              94.0

In [16]:
# Avg and Observation temp fields do not seem relevant to fill in missing high and low temps.

In [17]:
# Identify the specific records that have null values for each of the three key fields

Missing_Data_Precipitation = Missing_Data[Missing_Data['Precipitation (inches)'].isna()].index
Missing_Data_LowTemp = Missing_Data[Missing_Data['Lowest Hourly Temp (Fahrenheit)'].isna()].index
Missing_Data_HighTemp = Missing_Data[Missing_Data['Highest Hourly Temp (Fahrenheit)'].isna()].index
Missing_Data_HighTemp

Int64Index([15795, 18949, 18962, 19038, 19691, 19695, 19839, 19875, 19895,
            19997, 20120, 20134, 20148, 20160, 20162, 20219, 20245, 20248,
            20250, 20283, 20319, 20322, 20328, 20329, 20602, 20609, 20623,
            23264, 23265, 25703, 25869, 27442, 27443, 27628, 27757, 27845],
           dtype='int64')

In [18]:
# Test theory that average of day before and day after is close to temp on target date

low_difference = []

for i in weather_df.index:
    if i-1 in weather_df.index and i+1 in weather_df.index and not np.isnan(weather_df.loc[i-1,'Lowest Hourly Temp (Fahrenheit)']) and not np.isnan(weather_df.loc[i,'Lowest Hourly Temp (Fahrenheit)']) and not np.isnan(weather_df.loc[i+1,'Lowest Hourly Temp (Fahrenheit)']):
        low_difference.append(weather_df['Lowest Hourly Temp (Fahrenheit)'][i] - (weather_df['Lowest Hourly Temp (Fahrenheit)'][i-1] + weather_df['Lowest Hourly Temp (Fahrenheit)'][i+1])/2)

low_deviation = sum(low_difference) / len(low_difference)

low_deviation

0.0003349073981044241

In [19]:
high_difference = []

for i in weather_df.index:
    if i-1 in weather_df.index and i+1 in weather_df.index and not np.isnan(weather_df.loc[i-1,'Highest Hourly Temp (Fahrenheit)']) and not np.isnan(weather_df.loc[i,'Highest Hourly Temp (Fahrenheit)']) and not np.isnan(weather_df.loc[i+1,'Highest Hourly Temp (Fahrenheit)']):
        high_difference.append(weather_df['Highest Hourly Temp (Fahrenheit)'][i] - (weather_df['Highest Hourly Temp (Fahrenheit)'][i-1] + weather_df['Highest Hourly Temp (Fahrenheit)'][i+1])/2)

high_deviation = sum(high_difference) / len(high_difference)

high_deviation

0.0022097227802330252

In [20]:
# Temperature data is entered to the nearest tenth of a degree. 
# Deviations are less than one hundredth of a degree. 
# Will proceed with filling in records with average of day before and after.

In [21]:
# If the missing low record has a low record before and after it, average these two temps to fill in the missing value 

# Low temperature imputation
for i in Missing_Data_LowTemp:
    if i-1 in weather_df.index and i+1 in weather_df.index and not np.isnan(weather_df.loc[i-1,'Lowest Hourly Temp (Fahrenheit)']) and not np.isnan(weather_df.loc[i+1,'Lowest Hourly Temp (Fahrenheit)']):
        weather_df['Lowest Hourly Temp (Fahrenheit)'][i] = (weather_df['Lowest Hourly Temp (Fahrenheit)'][i-1] + weather_df['Lowest Hourly Temp (Fahrenheit)'][i+1])/2
        Missing_Data_LowTemp = Missing_Data_LowTemp.drop(i)

Missing_Data_LowTemp

/var/folders/n7/v6st_7m50r399qhl3pcqrdmh0000gn/T/ipykernel_3752/1489477954.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weather_df['Lowest Hourly Temp (Fahrenheit)'][i] = (weather_df['Lowest Hourly Temp (Fahrenheit)'][i-1] + weather_df['Lowest Hourly Temp (Fahrenheit)'][i+1])/2
/var/folders/n7/v6st_7m50r399qhl3pcqrdmh0000gn/T/ipykernel_3752/1489477954.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weather_df['Lowest Hourly Temp (Fahrenheit)'][i] = (weather_df['Lowest Hourly Temp (Fahrenheit)'][i-1] + weather_df['Lowest Hourly Temp (Fahrenheit)'][i+1])/2
/var/folders/n7/v6st_7m50r399qhl3pcqrdmh0000gn/T/ipykernel_3752/1489477954.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weather_df['Lowest Hourly Temp (Fahrenheit)'][i] = (weather_df['Lowest Hourly Temp (Fahrenheit)'][i-1] + weather_df['Lowest Hourly Temp (Fahrenheit)'][i+1])/2
/var/folders/n7/v6st_7m50r399qhl3pcqrdmh0000gn/T/ipykernel_3752/1489477954.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weather_df['Lowest Hourly Temp (Fahrenheit)'][i] = (weather_df['Lowest Hourly Temp (Fahrenheit)'][i-1] + weather_df['Lowest Hourly Temp (Fahrenheit)'][i+1])/2
/var/folders/n7/v6st_7m50r399qhl3pcqrdmh0000gn/T/ipykernel_3752/1489477954.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weather_df['Lowest Hourly Temp (Fahrenheit)'][i] = (weather_df['Lowest Hourly Temp (Fahrenheit)'][i-1] + weather_df['Lowest Hourly Temp (Fahrenheit)'][i+1])/2
/var/folders/n7/v6st_7m50r399qhl3pcqrdmh0000gn/T/ipykernel_3752/1489477954.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weather_df['Lowest Hourly Temp (Fahrenheit)'][i] = (weather_df['Lowest Hourly Temp (Fahrenheit)'][i-1] + weather_df['Lowest Hourly Temp (Fahrenheit)'][i+1])/2
/var/folders/n7/v6st_7m50r399qhl3pcqrdmh0000gn/T/ipykernel_3752/1489477954.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weather_df['Lowest Hourly Temp (Fahrenheit)'][i] = (weather_df['Lowest Hourly Temp (Fahrenheit)'][i-1] + weather_df['Lowest Hourly Temp (Fahrenheit)'][i+1])/2
/var/folders/n7/v6st_7m50r399qhl3pcqrdmh0000gn/T/ipykernel_3752/1489477954.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weather_df['Lowest Hourly Temp (Fahrenheit)'][i] = (weather_df['Lowest Hourly Temp (Fahrenheit)'][i-1] + weather_df['Lowest Hourly Temp (Fahrenheit)'][i+1])/2
/var/folders/n7/v6st_7m50r399qhl3pcqrdmh0000gn/T/ipykernel_3752/1489477954.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weather_df['Lowest Hourly Temp (Fahrenheit)'][i] = (weather_df['Lowest Hourly Temp (Fahrenheit)'][i-1] + weather_df['Lowest Hourly Temp (Fahrenheit)'][i+1])/2
/var/folders/n7/v6st_7m50r399qhl3pcqrdmh0000gn/T/ipykernel_3752/1489477954.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weather_df['Lowest Hourly Temp (Fahrenheit)'][i] = (weather_df['Lowest Hourly Temp (Fahrenheit)'][i-1] + weather_df['Lowest Hourly Temp (Fahrenheit)'][i+1])/2
/var/folders/n7/v6st_7m50r399qhl3pcqrdmh0000gn/T/ipykernel_3752/1489477954.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weather_df['Lowest Hourly Temp (Fahrenheit)'][i] = (weather_df['Lowest Hourly Temp (Fahrenheit)'][i-1] + weather_df['Lowest Hourly Temp (Fahrenheit)'][i+1])/2
/var/folders/n7/v6st_7m50r399qhl3pcqrdmh0000gn/T/ipykernel_3752/1489477954.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weather_df['Lowest Hourly Temp (Fahrenheit)'][i] = (weather_df['Lowest Hourly Temp (Fahrenheit)'][i-1] + weather_df['Lowest Hourly Temp (Fahrenheit)'][i+1])/2
/var/folders/n7/v6st_7m50r399qhl3pcqrdmh0000gn/T/ipykernel_3752/1489477954.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weather_df['Lowest Hourly Temp (Fahrenheit)'][i] = (weather_df['Lowest Hourly Temp (Fahrenheit)'][i-1] + weather_df['Lowest Hourly Temp (Fahrenheit)'][i+1])/2
/var/folders/n7/v6st_7m50r399qhl3pcqrdmh0000gn/T/ipykernel_3752/1489477954.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weather_df['Lowest Hourly Temp (Fahrenheit)'][i] = (weather_df['Lowest Hourly Temp (Fahrenheit)'][i-1] + weather_df['Lowest Hourly Temp (Fahrenheit)'][i+1])/2
/var/folders/n7/v6st_7m50r399qhl3pcqrdmh0000gn/T/ipykernel_3752/1489477954.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weather_df['Lowest Hourly Temp (Fahrenheit)'][i] = (weather_df['Lowest Hourly Temp (Fahrenheit)'][i-1] + weather_df['Lowest Hourly Temp (Fahrenheit)'][i+1])/2
/var/folders/n7/v6st_7m50r399qhl3pcqrdmh0000gn/T/ipykernel_3752/1489477954.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weather_df['Lowest Hourly Temp (Fahrenheit)'][i] = (weather_df['Lowest Hourly Temp (Fahrenheit)'][i-1] + weather_df['Lowest Hourly Temp (Fahrenheit)'][i+1])/2
/var/folders/n7/v6st_7m50r399qhl3pcqrdmh0000gn/T/ipykernel_3752/1489477954.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weather_df['Lowest Hourly Temp (Fahrenheit)'][i] = (weather_df['Lowest Hourly Temp (Fahrenheit)'][i-1] + weather_df['Lowest Hourly Temp (Fahrenheit)'][i+1])/2
/var/folders/n7/v6st_7m50r399qhl3pcqrdmh0000gn/T/ipykernel_3752/1489477954.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weather_df['Lowest Hourly Temp (Fahrenheit)'][i] = (weather_df['Lowest Hourly Temp (Fahrenheit)'][i-1] + weather_df['Lowest Hourly Temp (Fahrenheit)'][i+1])/2
/var/folders/n7/v6st_7m50r399qhl3pcqrdmh0000gn/T/ipykernel_3752/1489477954.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weather_df['Lowest Hourly Temp (Fahrenheit)'][i] = (weather_df['Lowest Hourly Temp (Fahrenheit)'][i-1] + weather_df['Lowest Hourly Temp (Fahrenheit)'][i+1])/2
/var/folders/n7/v6st_7m50r399qhl3pcqrdmh0000gn/T/ipykernel_3752/1489477954.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weather_df['Lowest Hourly Temp (Fahrenheit)'][i] = (weather_df['Lowest Hourly Temp (Fahrenheit)'][i-1] + weather_df['Lowest Hourly Temp (Fahrenheit)'][i+1])/2
/var/folders/n7/v6st_7m50r399qhl3pcqrdmh0000gn/T/ipykernel_3752/1489477954.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weather_df['Lowest Hourly Temp (Fahrenheit)'][i] = (weather_df['Lowest Hourly Temp (Fahrenheit)'][i-1] + weather_df['Lowest Hourly Temp (Fahrenheit)'][i+1])/2
/var/folders/n7/v6st_7m50r399qhl3pcqrdmh0000gn/T/ipykernel_3752/1489477954.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weather_df['Lowest Hourly Temp (Fahrenheit)'][i] = (weather_df['Lowest Hourly Temp (Fahrenheit)'][i-1] + weather_df['Lowest Hourly Temp (Fahrenheit)'][i+1])/2
/var/folders/n7/v6st_7m50r399qhl3pcqrdmh0000gn/T/ipykernel_3752/1489477954.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weather_df['Lowest Hourly Temp (Fahrenheit)'][i] = (weather_df['Lowest Hourly Temp (Fahrenheit)'][i-1] + weather_df['Lowest Hourly Temp (Fahrenheit)'][i+1])/2
/var/folders/n7/v6st_7m50r399qhl3pcqrdmh0000gn/T/ipykernel_3752/1489477954.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weather_df['Lowest Hourly Temp (Fahrenheit)'][i] = (weather_df['Lowest Hourly Temp (Fahrenheit)'][i-1] + weather_df['Lowest Hourly Temp (Fahrenheit)'][i+1])/2
/var/folders/n7/v6st_7m50r399qhl3pcqrdmh0000gn/T/ipykernel_3752/1489477954.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weather_df['Lowest Hourly Temp (Fahrenheit)'][i] = (weather_df['Lowest Hourly Temp (Fahrenheit)'][i-1] + weather_df['Lowest Hourly Temp (Fahrenheit)'][i+1])/2
/var/folders/n7/v6st_7m50r399qhl3pcqrdmh0000gn/T/ipykernel_3752/1489477954.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weather_df['Lowest Hourly Temp (Fahrenheit)'][i] = (weather_df['Lowest Hourly Temp (Fahrenheit)'][i-1] + weather_df['Lowest Hourly Temp (Fahrenheit)'][i+1])/2
/var/folders/n7/v6st_7m50r399qhl3pcqrdmh0000gn/T/ipykernel_3752/1489477954.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weather_df['Lowest Hourly Temp (Fahrenheit)'][i] = (weather_df['Lowest Hourly Temp (Fahrenheit)'][i-1] + weather_df['Lowest Hourly Temp (Fahrenheit)'][i+1])/2
/var/folders/n7/v6st_7m50r399qhl3pcqrdmh0000gn/T/ipykernel_3752/1489477954.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weather_df['Lowest Hourly Temp (Fahrenheit)'][i] = (weather_df['Lowest Hourly Temp (Fahrenheit)'][i-1] + weather_df['Lowest Hourly Temp (Fahrenheit)'][i+1])/2
/var/folders/n7/v6st_7m50r399qhl3pcqrdmh0000gn/T/ipykernel_3752/1489477954.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weather_df['Lowest Hourly Temp (Fahrenheit)'][i] = (weather_df['Lowest Hourly Temp (Fahrenheit)'][i-1] + weather_df['Lowest Hourly Temp (Fahrenheit)'][i+1])/2
/var/folders/n7/v6st_7m50r399qhl3pcqrdmh0000gn/T/ipykernel_3752/1489477954.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weather_df['Lowest Hourly Temp (Fahrenheit)'][i] = (weather_df['Lowest Hourly Temp (Fahrenheit)'][i-1] + weather_df['Lowest Hourly Temp (Fahrenheit)'][i+1])/2
/var/folders/n7/v6st_7m50r399qhl3pcqrdmh0000gn/T/ipykernel_3752/1489477954.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weather_df['Lowest Hourly Temp (Fahrenheit)'][i] = (weather_df['Lowest Hourly Temp (Fahrenheit)'][i-1] + weather_df['Lowest Hourly Temp (Fahrenheit)'][i+1])/2
/var/folders/n7/v6st_7m50r399qhl3pcqrdmh0000gn/T/ipykernel_3752/1489477954.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weather_df['Lowest Hourly Temp (Fahrenheit)'][i] = (weather_df['Lowest Hourly Temp (Fahrenheit)'][i-1] + weather_df['Lowest Hourly Temp (Fahrenheit)'][i+1])/2
/var/folders/n7/v6st_7m50r399qhl3pcqrdmh0000gn/T/ipykernel_3752/1489477954.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weather_df['Lowest Hourly Temp (Fahrenheit)'][i] = (weather_df['Lowest Hourly Temp (Fahrenheit)'][i-1] + weather_df['Lowest Hourly Temp (Fahrenheit)'][i+1])/2

Int64Index([20328, 20329, 23264, 23265, 27757, 27758], dtype='int64')

In [22]:
# High temperature imputation

for i in Missing_Data_HighTemp:
    if i-1 in weather_df.index and i+1 in weather_df.index and not np.isnan(weather_df.loc[i-1,'Highest Hourly Temp (Fahrenheit)']) and not np.isnan(weather_df.loc[i+1,'Highest Hourly Temp (Fahrenheit)']):
        weather_df['Highest Hourly Temp (Fahrenheit)'][i] = (weather_df['Highest Hourly Temp (Fahrenheit)'][i-1] + weather_df['Highest Hourly Temp (Fahrenheit)'][i+1])/2
        Missing_Data_HighTemp = Missing_Data_HighTemp.drop(i)

Missing_Data_HighTemp

/var/folders/n7/v6st_7m50r399qhl3pcqrdmh0000gn/T/ipykernel_3752/3639290448.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weather_df['Highest Hourly Temp (Fahrenheit)'][i] = (weather_df['Highest Hourly Temp (Fahrenheit)'][i-1] + weather_df['Highest Hourly Temp (Fahrenheit)'][i+1])/2
/var/folders/n7/v6st_7m50r399qhl3pcqrdmh0000gn/T/ipykernel_3752/3639290448.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weather_df['Highest Hourly Temp (Fahrenheit)'][i] = (weather_df['Highest Hourly Temp (Fahrenheit)'][i-1] + weather_df['Highest Hourly Temp (Fahrenheit)'][i+1])/2
/var/folders/n7/v6st_7m50r399qhl3pcqrdmh0000gn/T/ipykernel_3752/3639290448.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weather_df['Highest Hourly Temp (Fahrenheit)'][i] = (weather_df['Highest Hourly Temp (Fahrenheit)'][i-1] + weather_df['Highest Hourly Temp (Fahrenheit)'][i+1])/2
/var/folders/n7/v6st_7m50r399qhl3pcqrdmh0000gn/T/ipykernel_3752/3639290448.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weather_df['Highest Hourly Temp (Fahrenheit)'][i] = (weather_df['Highest Hourly Temp (Fahrenheit)'][i-1] + weather_df['Highest Hourly Temp (Fahrenheit)'][i+1])/2
/var/folders/n7/v6st_7m50r399qhl3pcqrdmh0000gn/T/ipykernel_3752/3639290448.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weather_df['Highest Hourly Temp (Fahrenheit)'][i] = (weather_df['Highest Hourly Temp (Fahrenheit)'][i-1] + weather_df['Highest Hourly Temp (Fahrenheit)'][i+1])/2
/var/folders/n7/v6st_7m50r399qhl3pcqrdmh0000gn/T/ipykernel_3752/3639290448.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weather_df['Highest Hourly Temp (Fahrenheit)'][i] = (weather_df['Highest Hourly Temp (Fahrenheit)'][i-1] + weather_df['Highest Hourly Temp (Fahrenheit)'][i+1])/2
/var/folders/n7/v6st_7m50r399qhl3pcqrdmh0000gn/T/ipykernel_3752/3639290448.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weather_df['Highest Hourly Temp (Fahrenheit)'][i] = (weather_df['Highest Hourly Temp (Fahrenheit)'][i-1] + weather_df['Highest Hourly Temp (Fahrenheit)'][i+1])/2
/var/folders/n7/v6st_7m50r399qhl3pcqrdmh0000gn/T/ipykernel_3752/3639290448.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weather_df['Highest Hourly Temp (Fahrenheit)'][i] = (weather_df['Highest Hourly Temp (Fahrenheit)'][i-1] + weather_df['Highest Hourly Temp (Fahrenheit)'][i+1])/2
/var/folders/n7/v6st_7m50r399qhl3pcqrdmh0000gn/T/ipykernel_3752/3639290448.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weather_df['Highest Hourly Temp (Fahrenheit)'][i] = (weather_df['Highest Hourly Temp (Fahrenheit)'][i-1] + weather_df['Highest Hourly Temp (Fahrenheit)'][i+1])/2
/var/folders/n7/v6st_7m50r399qhl3pcqrdmh0000gn/T/ipykernel_3752/3639290448.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weather_df['Highest Hourly Temp (Fahrenheit)'][i] = (weather_df['Highest Hourly Temp (Fahrenheit)'][i-1] + weather_df['Highest Hourly Temp (Fahrenheit)'][i+1])/2
/var/folders/n7/v6st_7m50r399qhl3pcqrdmh0000gn/T/ipykernel_3752/3639290448.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weather_df['Highest Hourly Temp (Fahrenheit)'][i] = (weather_df['Highest Hourly Temp (Fahrenheit)'][i-1] + weather_df['Highest Hourly Temp (Fahrenheit)'][i+1])/2
/var/folders/n7/v6st_7m50r399qhl3pcqrdmh0000gn/T/ipykernel_3752/3639290448.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weather_df['Highest Hourly Temp (Fahrenheit)'][i] = (weather_df['Highest Hourly Temp (Fahrenheit)'][i-1] + weather_df['Highest Hourly Temp (Fahrenheit)'][i+1])/2
/var/folders/n7/v6st_7m50r399qhl3pcqrdmh0000gn/T/ipykernel_3752/3639290448.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weather_df['Highest Hourly Temp (Fahrenheit)'][i] = (weather_df['Highest Hourly Temp (Fahrenheit)'][i-1] + weather_df['Highest Hourly Temp (Fahrenheit)'][i+1])/2
/var/folders/n7/v6st_7m50r399qhl3pcqrdmh0000gn/T/ipykernel_3752/3639290448.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weather_df['Highest Hourly Temp (Fahrenheit)'][i] = (weather_df['Highest Hourly Temp (Fahrenheit)'][i-1] + weather_df['Highest Hourly Temp (Fahrenheit)'][i+1])/2
/var/folders/n7/v6st_7m50r399qhl3pcqrdmh0000gn/T/ipykernel_3752/3639290448.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weather_df['Highest Hourly Temp (Fahrenheit)'][i] = (weather_df['Highest Hourly Temp (Fahrenheit)'][i-1] + weather_df['Highest Hourly Temp (Fahrenheit)'][i+1])/2
/var/folders/n7/v6st_7m50r399qhl3pcqrdmh0000gn/T/ipykernel_3752/3639290448.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weather_df['Highest Hourly Temp (Fahrenheit)'][i] = (weather_df['Highest Hourly Temp (Fahrenheit)'][i-1] + weather_df['Highest Hourly Temp (Fahrenheit)'][i+1])/2
/var/folders/n7/v6st_7m50r399qhl3pcqrdmh0000gn/T/ipykernel_3752/3639290448.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weather_df['Highest Hourly Temp (Fahrenheit)'][i] = (weather_df['Highest Hourly Temp (Fahrenheit)'][i-1] + weather_df['Highest Hourly Temp (Fahrenheit)'][i+1])/2
/var/folders/n7/v6st_7m50r399qhl3pcqrdmh0000gn/T/ipykernel_3752/3639290448.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weather_df['Highest Hourly Temp (Fahrenheit)'][i] = (weather_df['Highest Hourly Temp (Fahrenheit)'][i-1] + weather_df['Highest Hourly Temp (Fahrenheit)'][i+1])/2
/var/folders/n7/v6st_7m50r399qhl3pcqrdmh0000gn/T/ipykernel_3752/3639290448.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weather_df['Highest Hourly Temp (Fahrenheit)'][i] = (weather_df['Highest Hourly Temp (Fahrenheit)'][i-1] + weather_df['Highest Hourly Temp (Fahrenheit)'][i+1])/2
/var/folders/n7/v6st_7m50r399qhl3pcqrdmh0000gn/T/ipykernel_3752/3639290448.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weather_df['Highest Hourly Temp (Fahrenheit)'][i] = (weather_df['Highest Hourly Temp (Fahrenheit)'][i-1] + weather_df['Highest Hourly Temp (Fahrenheit)'][i+1])/2
/var/folders/n7/v6st_7m50r399qhl3pcqrdmh0000gn/T/ipykernel_3752/3639290448.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weather_df['Highest Hourly Temp (Fahrenheit)'][i] = (weather_df['Highest Hourly Temp (Fahrenheit)'][i-1] + weather_df['Highest Hourly Temp (Fahrenheit)'][i+1])/2
/var/folders/n7/v6st_7m50r399qhl3pcqrdmh0000gn/T/ipykernel_3752/3639290448.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weather_df['Highest Hourly Temp (Fahrenheit)'][i] = (weather_df['Highest Hourly Temp (Fahrenheit)'][i-1] + weather_df['Highest Hourly Temp (Fahrenheit)'][i+1])/2
/var/folders/n7/v6st_7m50r399qhl3pcqrdmh0000gn/T/ipykernel_3752/3639290448.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weather_df['Highest Hourly Temp (Fahrenheit)'][i] = (weather_df['Highest Hourly Temp (Fahrenheit)'][i-1] + weather_df['Highest Hourly Temp (Fahrenheit)'][i+1])/2
/var/folders/n7/v6st_7m50r399qhl3pcqrdmh0000gn/T/ipykernel_3752/3639290448.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weather_df['Highest Hourly Temp (Fahrenheit)'][i] = (weather_df['Highest Hourly Temp (Fahrenheit)'][i-1] + weather_df['Highest Hourly Temp (Fahrenheit)'][i+1])/2
/var/folders/n7/v6st_7m50r399qhl3pcqrdmh0000gn/T/ipykernel_3752/3639290448.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weather_df['Highest Hourly Temp (Fahrenheit)'][i] = (weather_df['Highest Hourly Temp (Fahrenheit)'][i-1] + weather_df['Highest Hourly Temp (Fahrenheit)'][i+1])/2
/var/folders/n7/v6st_7m50r399qhl3pcqrdmh0000gn/T/ipykernel_3752/3639290448.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weather_df['Highest Hourly Temp (Fahrenheit)'][i] = (weather_df['Highest Hourly Temp (Fahrenheit)'][i-1] + weather_df['Highest Hourly Temp (Fahrenheit)'][i+1])/2
/var/folders/n7/v6st_7m50r399qhl3pcqrdmh0000gn/T/ipykernel_3752/3639290448.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weather_df['Highest Hourly Temp (Fahrenheit)'][i] = (weather_df['Highest Hourly Temp (Fahrenheit)'][i-1] + weather_df['Highest Hourly Temp (Fahrenheit)'][i+1])/2
/var/folders/n7/v6st_7m50r399qhl3pcqrdmh0000gn/T/ipykernel_3752/3639290448.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weather_df['Highest Hourly Temp (Fahrenheit)'][i] = (weather_df['Highest Hourly Temp (Fahrenheit)'][i-1] + weather_df['Highest Hourly Temp (Fahrenheit)'][i+1])/2
/var/folders/n7/v6st_7m50r399qhl3pcqrdmh0000gn/T/ipykernel_3752/3639290448.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weather_df['Highest Hourly Temp (Fahrenheit)'][i] = (weather_df['Highest Hourly Temp (Fahrenheit)'][i-1] + weather_df['Highest Hourly Temp (Fahrenheit)'][i+1])/2
/var/folders/n7/v6st_7m50r399qhl3pcqrdmh0000gn/T/ipykernel_3752/3639290448.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weather_df['Highest Hourly Temp (Fahrenheit)'][i] = (weather_df['Highest Hourly Temp (Fahrenheit)'][i-1] + weather_df['Highest Hourly Temp (Fahrenheit)'][i+1])/2

Int64Index([20328, 20329, 23264, 23265, 27442, 27443], dtype='int64')

In [23]:
# For missing precipitation values, fill in with average of precipitation on that day
for i in Missing_Data_Precipitation:
    weather_df['Precipitation (inches)'][i] = round(weather_df[weather_df['Month & Day'] == weather_df['Month & Day'][i]]['Precipitation (inches)'].mean(),2)

/var/folders/n7/v6st_7m50r399qhl3pcqrdmh0000gn/T/ipykernel_3752/3600688816.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weather_df['Precipitation (inches)'][i] = round(weather_df[weather_df['Month & Day'] == weather_df['Month & Day'][i]]['Precipitation (inches)'].mean(),2)

In [24]:
# review remaining items with missing temp data
Missing_Data = Missing_Data_LowTemp.union(Missing_Data_HighTemp)
Missing_Data_Limit.loc[Missing_Data,:]

,NAME,DATE,Days in Multiday Precipitation,Multiday Precipitation Total (inches),Precipitation (inches),Snowfall (inches),Avg Hourly Temp (Fahrenheit),Highest Hourly Temp (Fahrenheit),Lowest Hourly Temp (Fahrenheit),Temperature at Observation (Fahrenheit),Water Equivalent of Snow on the Ground (inches),Water-equivalent of Snowfall (inches),Weather Type - Ice Pellets,Weather Type - Hail,Weather Type - Drizzle,Weather Type - Freezing Drizzle,Weather Type - Rain,Weather Type - Freezing Rain,Weather Type - Snow
20328,"KANSAS CITY DOWNTOWN AIRPORT, MO US",1996-12-27,NaN,NaN,0.00,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20329,"KANSAS CITY DOWNTOWN AIRPORT, MO US",1996-12-28,NaN,NaN,0.00,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23264,"KANSAS CITY DOWNTOWN AIRPORT, MO US",2005-01-10,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23265,"KANSAS CITY DOWNTOWN AIRPORT, MO US",2005-01-11,NaN,NaN,0.00,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27442,"KANSAS CITY DOWNTOWN AIRPORT, MO US",2016-06-19,NaN,NaN,0.00,NaN,NaN,NaN,73.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27443,"KANSAS CITY DOWNTOWN AIRPORT, MO US",2016-06-20,NaN,NaN,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27757,"KANSAS CITY DOWNTOWN AIRPORT, MO US",2017-04-30,NaN,NaN,0.12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27758,"KANSAS CITY DOWNTOWN AIRPORT, MO US",2017-05-01,NaN,NaN,0.00,NaN,NaN,62.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
# check temperature data surrounding records 20328 & 20329
weather_df.loc[20326:20331,{'DATE','Highest Hourly Temp (Fahrenheit)','Lowest Hourly Temp (Fahrenheit)'}]

/var/folders/n7/v6st_7m50r399qhl3pcqrdmh0000gn/T/ipykernel_3752/3223039279.py:2: FutureWarning: Passing a set as an indexer is deprecated and will raise in a future version. Use a list instead.
  weather_df.loc[20326:20331,{'DATE','Highest Hourly Temp (Fahrenheit)','Lowest Hourly Temp (Fahrenheit)'}]

,DATE,Lowest Hourly Temp (Fahrenheit),Highest Hourly Temp (Fahrenheit)
20326,1996-12-25,8.0,26.0
20327,1996-12-26,11.0,23.0
20328,1996-12-27,NaN,NaN
20329,1996-12-28,NaN,NaN
20330,1996-12-29,18.0,40.0
20331,1996-12-30,23.0,50.0

In [26]:
# impute average of 1996-12-26 & 1996-12-29 to missing fields
weather_df['Lowest Hourly Temp (Fahrenheit)'][20328] = (weather_df['Lowest Hourly Temp (Fahrenheit)'][20327] + weather_df['Lowest Hourly Temp (Fahrenheit)'][20330])/2
weather_df['Lowest Hourly Temp (Fahrenheit)'][20329] = (weather_df['Lowest Hourly Temp (Fahrenheit)'][20327] + weather_df['Lowest Hourly Temp (Fahrenheit)'][20330])/2
weather_df['Highest Hourly Temp (Fahrenheit)'][20328] = (weather_df['Highest Hourly Temp (Fahrenheit)'][20327] + weather_df['Highest Hourly Temp (Fahrenheit)'][20330])/2
weather_df['Highest Hourly Temp (Fahrenheit)'][20329] = (weather_df['Highest Hourly Temp (Fahrenheit)'][20327] + weather_df['Highest Hourly Temp (Fahrenheit)'][20330])/2
Missing_Data = Missing_Data.drop([20328,20329])
Missing_Data

/var/folders/n7/v6st_7m50r399qhl3pcqrdmh0000gn/T/ipykernel_3752/3729703290.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weather_df['Lowest Hourly Temp (Fahrenheit)'][20328] = (weather_df['Lowest Hourly Temp (Fahrenheit)'][20327] + weather_df['Lowest Hourly Temp (Fahrenheit)'][20330])/2
/var/folders/n7/v6st_7m50r399qhl3pcqrdmh0000gn/T/ipykernel_3752/3729703290.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weather_df['Lowest Hourly Temp (Fahrenheit)'][20329] = (weather_df['Lowest Hourly Temp (Fahrenheit)'][20327] + weather_df['Lowest Hourly Temp (Fahrenheit)'][20330])/2
/var/folders/n7/v6st_7m50r399qhl3pcqrdmh0000gn/T/ipykernel_3752/3729703290.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weather_df['Highest Hourly Temp (Fahrenheit)'][20328] = (weather_df['Highest Hourly Temp (Fahrenheit)'][20327] + weather_df['Highest Hourly Temp (Fahrenheit)'][20330])/2
/var/folders/n7/v6st_7m50r399qhl3pcqrdmh0000gn/T/ipykernel_3752/3729703290.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weather_df['Highest Hourly Temp (Fahrenheit)'][20329] = (weather_df['Highest Hourly Temp (Fahrenheit)'][20327] + weather_df['Highest Hourly Temp (Fahrenheit)'][20330])/2

Int64Index([23264, 23265, 27442, 27443, 27757, 27758], dtype='int64')

In [27]:
# check temperature data surrounding records 27442 & 27443
weather_df.loc[27440:27445,{'DATE','Highest Hourly Temp (Fahrenheit)','Lowest Hourly Temp (Fahrenheit)'}]

/var/folders/n7/v6st_7m50r399qhl3pcqrdmh0000gn/T/ipykernel_3752/3892168885.py:2: FutureWarning: Passing a set as an indexer is deprecated and will raise in a future version. Use a list instead.
  weather_df.loc[27440:27445,{'DATE','Highest Hourly Temp (Fahrenheit)','Lowest Hourly Temp (Fahrenheit)'}]

,DATE,Lowest Hourly Temp (Fahrenheit),Highest Hourly Temp (Fahrenheit)
27440,2016-06-17,78.0,95.0
27441,2016-06-18,74.0,91.0
27442,2016-06-19,73.0,NaN
27443,2016-06-20,74.5,NaN
27444,2016-06-21,76.0,97.0
27445,2016-06-22,82.0,101.0

In [28]:
# impute average of 2016-06-18 & 2016-06-21 to missing fields

weather_df['Highest Hourly Temp (Fahrenheit)'][27442] = (weather_df['Highest Hourly Temp (Fahrenheit)'][27441] + weather_df['Highest Hourly Temp (Fahrenheit)'][27444])/2
weather_df['Highest Hourly Temp (Fahrenheit)'][27443] = (weather_df['Highest Hourly Temp (Fahrenheit)'][27441] + weather_df['Highest Hourly Temp (Fahrenheit)'][27444])/2
Missing_Data = Missing_Data.drop([27442,27443])
Missing_Data

/var/folders/n7/v6st_7m50r399qhl3pcqrdmh0000gn/T/ipykernel_3752/2155220673.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weather_df['Highest Hourly Temp (Fahrenheit)'][27442] = (weather_df['Highest Hourly Temp (Fahrenheit)'][27441] + weather_df['Highest Hourly Temp (Fahrenheit)'][27444])/2
/var/folders/n7/v6st_7m50r399qhl3pcqrdmh0000gn/T/ipykernel_3752/2155220673.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weather_df['Highest Hourly Temp (Fahrenheit)'][27443] = (weather_df['Highest Hourly Temp (Fahrenheit)'][27441] + weather_df['Highest Hourly Temp (Fahrenheit)'][27444])/2

Int64Index([23264, 23265, 27757, 27758], dtype='int64')

In [29]:
# check temperature data surrounding records 23264 & 23265
weather_df.loc[23262:23267,{'DATE','Highest Hourly Temp (Fahrenheit)','Lowest Hourly Temp (Fahrenheit)'}]

/var/folders/n7/v6st_7m50r399qhl3pcqrdmh0000gn/T/ipykernel_3752/43699583.py:2: FutureWarning: Passing a set as an indexer is deprecated and will raise in a future version. Use a list instead.
  weather_df.loc[23262:23267,{'DATE','Highest Hourly Temp (Fahrenheit)','Lowest Hourly Temp (Fahrenheit)'}]

,DATE,Lowest Hourly Temp (Fahrenheit),Highest Hourly Temp (Fahrenheit)
23262,2005-01-08,19.0,31.0
23263,2005-01-09,28.0,44.0
23264,2005-01-10,NaN,NaN
23265,2005-01-11,NaN,NaN
23266,2005-01-12,30.0,36.0
23267,2005-01-13,9.0,30.0

In [30]:
# impute average of 2005-01-09 & 2005-01-12 to missing fields
weather_df['Lowest Hourly Temp (Fahrenheit)'][23264] = (weather_df['Lowest Hourly Temp (Fahrenheit)'][23263] + weather_df['Lowest Hourly Temp (Fahrenheit)'][23266])/2
weather_df['Lowest Hourly Temp (Fahrenheit)'][23265] = (weather_df['Lowest Hourly Temp (Fahrenheit)'][23263] + weather_df['Lowest Hourly Temp (Fahrenheit)'][23266])/2
weather_df['Highest Hourly Temp (Fahrenheit)'][23264] = (weather_df['Highest Hourly Temp (Fahrenheit)'][23263] + weather_df['Highest Hourly Temp (Fahrenheit)'][23266])/2
weather_df['Highest Hourly Temp (Fahrenheit)'][23265] = (weather_df['Highest Hourly Temp (Fahrenheit)'][23263] + weather_df['Highest Hourly Temp (Fahrenheit)'][23266])/2
Missing_Data = Missing_Data.drop([23264,23265])
Missing_Data

/var/folders/n7/v6st_7m50r399qhl3pcqrdmh0000gn/T/ipykernel_3752/1483561811.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weather_df['Lowest Hourly Temp (Fahrenheit)'][23264] = (weather_df['Lowest Hourly Temp (Fahrenheit)'][23263] + weather_df['Lowest Hourly Temp (Fahrenheit)'][23266])/2
/var/folders/n7/v6st_7m50r399qhl3pcqrdmh0000gn/T/ipykernel_3752/1483561811.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weather_df['Lowest Hourly Temp (Fahrenheit)'][23265] = (weather_df['Lowest Hourly Temp (Fahrenheit)'][23263] + weather_df['Lowest Hourly Temp (Fahrenheit)'][23266])/2
/var/folders/n7/v6st_7m50r399qhl3pcqrdmh0000gn/T/ipykernel_3752/1483561811.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weather_df['Highest Hourly Temp (Fahrenheit)'][23264] = (weather_df['Highest Hourly Temp (Fahrenheit)'][23263] + weather_df['Highest Hourly Temp (Fahrenheit)'][23266])/2
/var/folders/n7/v6st_7m50r399qhl3pcqrdmh0000gn/T/ipykernel_3752/1483561811.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weather_df['Highest Hourly Temp (Fahrenheit)'][23265] = (weather_df['Highest Hourly Temp (Fahrenheit)'][23263] + weather_df['Highest Hourly Temp (Fahrenheit)'][23266])/2

Int64Index([27757, 27758], dtype='int64')

In [31]:
# check temperature data surrounding records 27757 & 27758
weather_df.loc[27755:27760,{'DATE','Highest Hourly Temp (Fahrenheit)','Lowest Hourly Temp (Fahrenheit)'}]

/var/folders/n7/v6st_7m50r399qhl3pcqrdmh0000gn/T/ipykernel_3752/1473849185.py:2: FutureWarning: Passing a set as an indexer is deprecated and will raise in a future version. Use a list instead.
  weather_df.loc[27755:27760,{'DATE','Highest Hourly Temp (Fahrenheit)','Lowest Hourly Temp (Fahrenheit)'}]

,DATE,Lowest Hourly Temp (Fahrenheit),Highest Hourly Temp (Fahrenheit)
27755,2017-04-28,47.0,66.0
27756,2017-04-29,46.0,50.0
27757,2017-04-30,NaN,56.0
27758,2017-05-01,NaN,62.0
27759,2017-05-02,49.0,68.0
27760,2017-05-03,46.0,56.0

In [32]:
# impute average of 2017-04-29 & 2017-05-02 to missing fields

weather_df['Lowest Hourly Temp (Fahrenheit)'][27757] = (weather_df['Lowest Hourly Temp (Fahrenheit)'][27756] + weather_df['Lowest Hourly Temp (Fahrenheit)'][27759])/2
weather_df['Lowest Hourly Temp (Fahrenheit)'][27758] = (weather_df['Lowest Hourly Temp (Fahrenheit)'][27756] + weather_df['Lowest Hourly Temp (Fahrenheit)'][27759])/2
Missing_Data = Missing_Data.drop([27757,27758])
Missing_Data

/var/folders/n7/v6st_7m50r399qhl3pcqrdmh0000gn/T/ipykernel_3752/2937368557.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weather_df['Lowest Hourly Temp (Fahrenheit)'][27757] = (weather_df['Lowest Hourly Temp (Fahrenheit)'][27756] + weather_df['Lowest Hourly Temp (Fahrenheit)'][27759])/2
/var/folders/n7/v6st_7m50r399qhl3pcqrdmh0000gn/T/ipykernel_3752/2937368557.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weather_df['Lowest Hourly Temp (Fahrenheit)'][27758] = (weather_df['Lowest Hourly Temp (Fahrenheit)'][27756] + weather_df['Lowest Hourly Temp (Fahrenheit)'][27759])/2

Int64Index([], dtype='int64')

In [ ]:
years = list(map(str, range(1934,2023)))
years

## Unnecessary Data

Look for the different types of unnecessary data in your dataset and address it as needed. Make sure to use code comments to illustrate your thought process.

In [ ]:
# Remove NKC station.  As determined in Checkpoint 2, the data span is not significant and there is no max and min temperature data.

weather_df = weather_df[weather_df['STATION']=='USW00013988']
weather_df.tail()

In [ ]:
# Review column information

weather_df.info()

In [ ]:
# remove all columns with less than 5% coverage

total_records = len(weather_df.index)

columns_to_delete = []

for column in weather_df.columns:
    if weather_df[column].notnull().sum() < (total_records * 0.05):
        columns_to_delete.append(column)

weather_df.drop(weather_df.loc[:,columns_to_delete], axis=1,inplace=True)

# Review remaining columns
weather_df.info()

In [ ]:
# Remove remaining irrelevant columns

irrelevant_columns = ['Avg Daily Cloudiness (%)',
                      'Avg Solar Day Cloudiness (%)',
                      'Avg Daily Wind Speed (mph)',
                      'Fastest Wind Time (HH:MM)',
                      'Distance Between River and Gauge Height (inches)',
                      'Peak Gust Time (HH:MM)',
                      'Daily % of Possible Sunshine',
                      'Direction of Fastest 2-Minute Wind (degrees)',
                      'Direction of Fastest 5-Minute Wind (degrees)',
                      'Fastest mile wind direction (degrees)',
                      'Fastest 2-minute wind speed (mph)',
                      'Fastest 5-minute wind speed (mph)',
                      'Fastest mile wind speed (mph)',
                      'Weather Type - Fog','Weather Type - Thunder',
                      'Weather Type - Smoke or Haze',
                      'Weather Type - Rain','Weather Type - Snow',
                      'Daily Total Sunshine (minutes)']

weather_df.drop(weather_df.loc[:,irrelevant_columns], axis=1,inplace=True)

weather_df.head()

## Irregular Data

Detect outliers in your dataset and handle them as needed. Use code comments to make notes about your thought process.

## Inconsistent Data

Check for inconsistent data and address any that arises. As always, use code comments to illustrate your thought process.

## Summarize Your Results

Make note of your answers to the following questions.

1. Did you find all four types of dirty data in your dataset?
2. Did the process of cleaning your data give you new insights into your dataset?
3. Is there anything you would like to make note of when it comes to manipulating the data and making visualizations?